// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmmtgnjwhpeackuieejd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtbXRnbmp3aHBlYWNrdWllZWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDAxMzYsImV4cCI6MjA2NTUxNjEzNn0.etAxN3ZQLZcus-UONjGwjp5-uasUKBRp_67wABaawJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);